### ISSUE TITLE
apply(add_type_count)疑问

### ISSUE THREAD

**Issue by yyz1542685121** [daoliker/JData#12]
create_item_table有一行代码:
df_ac = df_ac.groupby(['sku_id'], as_index=False).apply(add_type_count)

跟踪发现对于第一个分组add_type_count会调用两次，这是为什么啊？

**Comment by daoliker** [comment]
应该是第一个分组有特殊情况,由于时间久远暂时无法相关细节. 建议可以试着用简单的例子一步步将结果打印出来进行调试
