### ISSUE TITLE
数据集从哪里可以下载？

### ISSUE THREAD

**Issue by CrazyAk** [daoliker/JData#16]

**Comment by skyswordLi** [comment]
同问，data目录下面已经没有数据文件了

**Comment by daoliker** [comment]
@CrazyAk @skyswordLi 由于在官方未找到下载链接, 已经将我之前的下载的上传到云盘, 请仅个人使用.
PS:
 _链接: https://pan.baidu.com/s/1eRR4Frc 密码: p6kn_
