### ISSUE TITLE
数据下载及其他

### ISSUE THREAD

**Issue by daoliker** [daoliker/JData#17]
(1) 之前因为特殊原因停止更新后期相关内容, 很抱歉, 之后将择期继续更新.
(2) 由于在官方未找到下载链接, 已经将我之前的下载的上传到云盘, 请仅个人使用.
PS:
 _链接: https://pan.baidu.com/s/1eRR4Frc 密码: p6kn_

**Comment by Nelsonlin0321** [comment]
感谢分享
