### ISSUE TITLE
关于create_user_table.py错误的问题

### ISSUE THREAD

**Issue by hgfm** [daoliker/JData#2]
环境python3.5.2，提示错误如下
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcb in position 5: invalid continuation byte
经测试似乎是JData_User_New.csv中age一栏的“岁”导致

如果使用记事本打开JData_User_New.csv，保存为utf-8格式，则在运行时会提示"['user_id'] not in index"
暂时不知如何解决，求解决方案

**Comment by ZS167275** [comment]
设置编码为 utf-8 并且读取 csv的时候设置编码为 gbk 
 #-*- coding=utf-8 -*- 
user = pd.read_csv('jdata/JData_User.csv',encoding="gb2312")
