### ISSUE TITLE
create_user_table.py中的获取用户csv的文件名有错误

### ISSUE THREAD

**Issue by ZS167275** [daoliker/JData#4]

**Comment by daoliker** [comment]
是什么样的错误？请把具体出错的代码贴下

**Comment by ZS167275** [comment]
USER_FILE = "data/JData_User.csv"
NEW_USER_FILE = "data/JData_User_New.csv"
USER_TABLE_FILE = "data/user_table.csv"


def get_from_jdata_user():
    df_usr = pd.read_csv(NEW_USER_FILE, header=0)
    df_usr = df_usr[["user_id", "age", "sex", "user_lv_cd"]]
    return df_usr


小问题，读错文件了

**Comment by daoliker** [comment]
这个是从做完年龄映射的NEW_USER_FILE中读取,
 这步之前需要先运行explore_data.py中的tranform_user_age函数,
我已经在最新版本中添加了相关注释

**Comment by ZS167275** [comment]
ok  一般研究你的思路 一般学 pandas 谢谢
